# Generated by Django 2.1.4 on 2018-12-05 22:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_file_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='server.User'),
        ),
    ]
