# Generated by Django 2.1.4 on 2018-12-05 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_auto_20181205_2206'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='owner',
            new_name='user',
        ),
    ]
