# Generated by Django 2.1.4 on 2018-12-06 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0007_auto_20181205_2358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('user', 'file')},
        ),
    ]
