# Generated by Django 2.1.4 on 2018-12-06 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_auto_20181206_0024'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='key',
            field=models.CharField(default=23, max_length=512),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='mac',
            field=models.CharField(default='d', max_length=512),
            preserve_default=False,
        ),
    ]
