# Generated by Django 2.1.4 on 2018-12-06 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_auto_20181206_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.BinaryField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.BinaryField(default=b'\x11\xc6\x1f\x04\xe5\xf9\x08!\x9d\xf8\xe8J\xd9\xf4L\x81\xe2G\x96\xe1\xbaF\x16\xcd\xe1\xeaAinDU\xdb', max_length=512),
        ),
        migrations.AlterField(
            model_name='file',
            name='mac',
            field=models.BinaryField(default='', max_length=512),
        ),
    ]
