# Generated by Django 2.1.4 on 2018-12-06 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0010_auto_20181206_0310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.BinaryField(default=None),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.BinaryField(default=b'I\xe7\r\x93\\r\xad\xc7\xc0\x98\x84X\x13{\xba\xaa;\xc9\xa6l\x12T\xf8\xa3\xbe>\xe7\x8c.:\xf6H', max_length=512),
        ),
        migrations.AlterField(
            model_name='file',
            name='mac',
            field=models.BinaryField(default=None, max_length=512),
        ),
    ]
