# Generated by Django 2.1.4 on 2018-12-06 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0011_auto_20181206_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.BinaryField(default=b''),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.BinaryField(default=b"\xe2'hH\xb4[Z\xdfH\xf1\x08\xaa\xd0\xbcD\xd0\x9a\n\x00l\xac??/\xd6%f\xdd\x8dg\xf9U", max_length=512),
        ),
    ]
