# Generated by Django 2.1.4 on 2018-12-06 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0012_auto_20181206_0316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(default=b''),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.CharField(default=b'xKCax0lLIQ2tbCmsPVcNYBrwgGPRaWLTOi4Tl3sfjN8=', max_length=32),
        ),
        migrations.AlterField(
            model_name='file',
            name='mac',
            field=models.CharField(max_length=64),
        ),
    ]
