# Generated by Django 2.1.4 on 2018-12-06 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0013_auto_20181206_0357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.BinaryField(default=b'PLwOTsN-lw6eN5CMNeSUBZexZaj7vCtBCcWDCElhxYg=', max_length=32),
        ),
    ]
