# Generated by Django 2.1.4 on 2018-12-06 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0014_auto_20181206_0412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='content',
            field=models.BinaryField(default=''),
        ),
        migrations.AlterField(
            model_name='file',
            name='key',
            field=models.BinaryField(default=b'-_0G9nNKX8Itfu_3edxLLJ6NF7RirfFjhbkPasnLLzA=', max_length=32),
        ),
    ]
